### ISSUE TITLE
undefiend reference errors when compiling hello_cpp_world

### ISSUE THREAD

**Issue by Wh0ba** [vitasdk/samples#55]
I've freshly installed vitasdk and when trying to compile the cpp sample "hello_cpp_world"  I get this error when running `make` 

```
[ 16%] Linking CXX executable hello_cpp_world
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::~pool()':
eh_alloc.cc:(.text._ZN12_GLOBAL__N_14poolD2Ev+0x4): undefined reference to `pthread_mutex_destroy'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::free(void*) [clone .constprop.0]':
eh_alloc.cc:(.text._ZN12_GLOBAL__N_14pool4freeEPv.constprop.0+0xe): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: eh_alloc.cc:(.text._ZN12_GLOBAL__N_14pool4freeEPv.constprop.0+0x78): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::allocate(unsigned int) [clone .constprop.0]':
eh_alloc.cc:(.text._ZN12_GLOBAL__N_14pool8allocateEj.constprop.0+0xe): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: eh_alloc.cc:(.text._ZN12_GLOBAL__N_14pool8allocateEj.constprop.0+0x4e): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_alloc.o): in function `_GLOBAL__sub_I__ZN9__gnu_cxx9__freeresEv':
eh_alloc.cc:(.text.startup._GLOBAL__sub_I__ZN9__gnu_cxx9__freeresEv+0x12): undefined reference to `pthread_mutex_init'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(guard.o): in function `(anonymous namespace)::mutex_wrapper::~mutex_wrapper() [clone .part.0]':
guard.cc:(.text._ZN12_GLOBAL__N_113mutex_wrapperD2Ev.part.0+0xc): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(guard.o): in function `__cxa_guard_acquire':
guard.cc:(.text.__cxa_guard_acquire+0x34): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_acquire+0x3a): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_acquire+0x66): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_acquire+0x7e): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_acquire+0x86): undefined reference to `pthread_cond_wait'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_acquire+0x94): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_acquire+0xc2): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(guard.o): in function `__cxa_guard_abort':
guard.cc:(.text.__cxa_guard_abort+0x14): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_abort+0x22): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_abort+0x3c): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_abort+0x4a): undefined reference to `pthread_cond_broadcast'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_abort+0x52): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(guard.o): in function `__cxa_guard_release':
guard.cc:(.text.__cxa_guard_release+0x14): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_release+0x22): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_release+0x44): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_release+0x52): undefined reference to `pthread_cond_broadcast'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: guard.cc:(.text.__cxa_guard_release+0x5a): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_globals.o): in function `__eh_globals_init::~__eh_globals_init()':
eh_globals.cc:(.text._ZN17__eh_globals_initD2Ev[_ZN17__eh_globals_initD5Ev]+0xe): undefined reference to `pthread_key_delete'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_globals.o): in function `__cxa_get_globals_fast':
eh_globals.cc:(.text.__cxa_get_globals_fast+0x18): undefined reference to `pthread_getspecific'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_globals.o): in function `__cxa_get_globals':
eh_globals.cc:(.text.__cxa_get_globals+0x1c): undefined reference to `pthread_getspecific'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: eh_globals.cc:(.text.__cxa_get_globals+0x34): undefined reference to `pthread_setspecific'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(eh_globals.o): in function `_GLOBAL__sub_I___cxa_get_globals_fast':
eh_globals.cc:(.text.startup._GLOBAL__sub_I___cxa_get_globals_fast+0x18): undefined reference to `pthread_key_create'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale.o): in function `__gnu_cxx::__mutex::~__mutex()':
locale.cc:(.text._ZN9__gnu_cxx7__mutexD2Ev[_ZN9__gnu_cxx7__mutexD5Ev]+0x4): undefined reference to `pthread_mutex_destroy'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale.o): in function `__gnu_cxx::__scoped_lock::~__scoped_lock()':
locale.cc:(.text._ZN9__gnu_cxx13__scoped_lockD2Ev[_ZN9__gnu_cxx13__scoped_lockD5Ev]+0x6): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale.o): in function `std::locale::facet::_S_get_c_locale()':
locale.cc:(.text._ZNSt6locale5facet15_S_get_c_localeEv+0x12): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale.o): in function `std::locale::_Impl::_M_install_cache(std::locale::facet const*, unsigned int)':
locale.cc:(.text._ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEj+0x28): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: locale.cc:(.text._ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEj+0x82): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: locale.cc:(.text._ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEj+0xcc): undefined reference to `pthread_mutex_init'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale_init.o): in function `(anonymous namespace)::get_locale_mutex()':
locale_init.cc:(.text._ZN12_GLOBAL__N_116get_locale_mutexEv+0x32): undefined reference to `pthread_mutex_init'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale_init.o): in function `std::locale::_S_initialize()':
locale_init.cc:(.text._ZNSt6locale13_S_initializeEv+0x1a): undefined reference to `pthread_once'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale_init.o): in function `std::locale::locale()':
locale_init.cc:(.text._ZNSt6localeC2Ev+0x2c): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: locale_init.cc:(.text._ZNSt6localeC2Ev+0x50): undefined reference to `pthread_mutex_unlock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/lib/libstdc++.a(locale_init.o): in function `std::locale::global(std::locale const&)':
locale_init.cc:(.text._ZNSt6locale6globalERKS_+0x12): undefined reference to `pthread_mutex_lock'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: locale_init.cc:(.text._ZNSt6locale6globalERKS_+0x74): undefined reference to `pthread_mutex_unlock'
collect2: error: ld returned 1 exit status
CMakeFiles/hello_cpp_world.dir/build.make:94: recipe for target 'hello_cpp_world' failed
make[2]: *** [hello_cpp_world] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/hello_cpp_world.dir/all' failed
make[1]: *** [CMakeFiles/hello_cpp_world.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Rinnegatamante** [comment]
Add pthread here: https://github.com/vitasdk/samples/blob/master/hello_cpp_world/CMakeLists.txt#L58

Should solve the issue.

**Comment by Wh0ba** [comment]
> 
> 
> Add pthread here: https://github.com/vitasdk/samples/blob/master/hello_cpp_world/CMakeLists.txt#L58
> 
> Should solve the issue.

nope still the same error :/
even when trying to manually compile it on the command line with `-lpthread` it still fails with the same errors

**Comment by rhyacinth** [comment]
You have to add both stdc++ and pthread to the place Rinnegatamante showed. stdc++ must be before pthread

**Comment by Wh0ba** [comment]
> 
> 
> You have to add both stdc++ and pthread to the place Rinnegatamante showed. stdc++ must be before pthread

OMG it worked 
thank you sooo much
